/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f95fdf95-3968-402c-b046-e7a2309cf945",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_41EWLm533",
    "aws_user_pools_web_client_id": "4kra60bat10ausoo4rr8e2g32",
    "oauth": {},
    "federationTarget": "COGNITO_IDENTITY_POOLS"
};


export default awsmobile;
